model:
  model_path: /root/bayes-tmp/jiayi/hf_models/lingbot-vla-4b
  tokenizer_path: /root/bayes-tmp/jiayi/hf_models/Qwen2.5-VL-3B-Instruct

data:
  datasets_type: vla
  data_name: kuavo
  train_path: /root/bayes-tmp/kuavo_dataset/task2_pick_apple_messy_lerobot/lerobot_v3.0
  joints:
    - arm.position: 14
    - effector.position: 2
  cameras:
    - head_cam_h
    - wrist_cam_l
    - wrist_cam_r
  num_workers: 4
  norm_type: meanstd
  norm_stats_file: assets/norm_stats/kuavo_apple.json

train:
  use_wandb: true
  wandb_project: lingbotvla
  wandb_name: apple_lora
  output_dir: ../../../outputs/kuavo_lingbotvla/task2_apple_lora/vlm_action_bs1_ga4
  chunk_size: 50

  data_parallel_mode: fsdp2
  enable_full_shard: false
  module_fsdp_enable: true

  use_compile: false
  rmpad: false
  rmpad_with_pos_ids: false
  ulysses_parallel_size: 1

  freeze_vision_encoder: false
  train_expert_only: false

  tokenizer_max_length: 72

  action_dim: 16
  max_action_dim: 75
  max_state_dim: 75

  lr: 5.0e-5
  lr_warmup_ratio: 0.05
  lr_decay_style: cosine
  weight_decay: 0.01

  micro_batch_size: 1
  gradient_accumulation_steps: 4

  num_train_epochs: 10
  max_steps: 1000000000

  ckpt_manager: dcp
  save_steps: 0
  save_epochs: 2
  save_hf_weights: false
  max_checkpoints_to_keep: 10

  enable_mixed_precision: true
  enable_fp32: false
  enable_resume: true
  enable_gradient_checkpointing: true

  use_lora: true
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.10

  lora_target_modules: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj,qkv,proj

  lora_target_scope: model.qwenvl_with_expert.qwen_expert.model.layers,model.qwenvl_with_expert.qwenvl.model.layers,model.qwenvl_with_expert.qwenvl.visual.blocks.30,model.qwenvl_with_expert.qwenvl.visual.blocks.31

  lora_trainable_modules: model.state_proj,model.action_in_proj,model.action_out_proj,model.action_time_mlp_in,model.action_time_mlp_out,model.time_mlp_in,model.time_mlp_out

  norm_qkv: false
  vlm_causal: false
  loss_type: fm
  align_params: {}