env:  # 推理环境设置
  inference_env: real  # 选仿真还是真机 option: sim/real
  platform_type: "4pro"  # 机器人型号
  which_arm: both  # 控制左手、右手还是双手
  eef_type: qiangnao  # 夹爪或手型类型
  ros_rate: 5  # 推理频率
  direct_to_wbc: false  # 是否使用direct to wbc模式。
  enable_action_interpolation: true
  control_rate: 100  # WBC插值后的实际控制指令频率
  

inference:  # 推理和评测设置
  go_bag_path: /home/kuavo/yuanmeng/start_bag/startbag_bottlepick_clipped.bag
  # /home/kuavo/yuanmeng/start_bag/startbag_bottlepick_clipped.bag     # bag 回放路径
  policy_type: client  # 要加载的模型类型,外挂模式选择client, 选择client模式后下面的pretrained_path失去作用
  pretrained_path: /path/to/checkpoint  # 要加载的权重路径。
  eval_episodes: 10  # 评测跑多少条
  max_episode_steps: 200  # 每条最多跑多少步

  task_prompt: "pick up the red apple from the table."
