_train_steps:
    value: 872
_wandb:
    value:
        cli_version: 0.28.2
        e:
            no96l6rjbdkf54mg015pe7ihyick0hty:
                args:
                    - configs/vla/kuavo_real_lora_package.yaml
                codePath: kuavo_model/external_models/lingbot-vla/tasks/vla/train_lingbotvla.py
                codePathLocal: tasks/vla/train_lingbotvla.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "55834574848"
                        used: "54707118080"
                email: jiay.wang@tum.de
                executable: /root/bayes-tmp/conda/envs/lingbotvla/bin/python3.12
                git:
                    commit: 878c0b08d4cc297d162df0442f4546d63267553a
                    remote: https://github.com/LejuRobotics/kuavo_learning_studio.git
                gpu: NVIDIA GeForce RTX 4090 D
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-7d180854-31c5-2eb2-35f3-db627dc916d5
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-2d529cf7-a614-c001-d8ca-27e31eb6d005
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-760a7e19-43e9-9493-65c3-f4e9005b05b2
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-bf1683f6-d12c-e75f-6003-ae98ede8bc4d
                host: 87dbbff6453d
                memory:
                    total: "270095302656"
                os: Linux-5.15.0-25-generic-x86_64-with-glibc2.35
                program: /root/bayes-tmp/jiayi/kuavo_learning_studio/kuavo_model/external_models/lingbot-vla/tasks/vla/train_lingbotvla.py
                python: CPython 3.12.13
                root: /root/bayes-tmp/jiayi/kuavo_learning_studio/kuavo_model/external_models/lingbot-vla
                startedAt: "2026-08-23T13:53:19.922529Z"
                writerId: no96l6rjbdkf54mg015pe7ihyick0hty
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.28.2
            "6": 4.51.3
            "12": 0.28.2
            "13": linux-x86_64
action_dim:
    value: null
activation_gpu_limit:
    value: 0
adanorm_time:
    value: true
adapt_to_pi_aloha:
    value: false
attn_implementation:
    value: flash_attention_2
basic_modules:
    value: []
bsz_warmup_init_mbtoken:
    value: 200
bsz_warmup_ratio:
    value: 0
cameras:
    value:
        - head_cam_h
        - wrist_cam_l
        - wrist_cam_r
chat_template:
    value: default
chunk_size:
    value: 50
ckpt_manager:
    value: dcp
config_path:
    value: /root/bayes-tmp/jiayi/hf_models/lingbot-vla-4b
context_parallel_size:
    value: 1
data_name:
    value: kuavo
data_parallel_mode:
    value: fsdp2
data_parallel_replicate_size:
    value: 1
data_parallel_shard_size:
    value: 1
data_parallel_size:
    value: 1
data_type:
    value: conversation
dataloader_batch_size:
    value: 16
dataloader_type:
    value: native
datasets_type:
    value: vla
decayed_max_grad_norm:
    value: 1
drop_last:
    value: true
dyn_bsz:
    value: true
dyn_bsz_buffer_size:
    value: 200
dyn_bsz_margin:
    value: 0
empty_cache_steps:
    value: 500
enable_activation_offload:
    value: false
enable_expert_vision:
    value: false
enable_forward_prefetch:
    value: true
enable_fp32:
    value: true
enable_fsdp_offload:
    value: false
enable_full_determinism:
    value: false
enable_full_shard:
    value: false
enable_gradient_checkpointing:
    value: true
enable_mixed_precision:
    value: true
enable_profiling:
    value: false
enable_reentrant:
    value: false
enable_resume:
    value: true
expert_parallel_size:
    value: 1
expert_vision_path:
    value: null
expert_vision_type:
    value: null
final_norm_adanorm:
    value: false
force_use_huggingface:
    value: false
freeze_vision_encoder:
    value: false
freeze_vit:
    value: false
global_batch_size:
    value: 16
global_rank:
    value: 0
gradient_accumulation_steps:
    value: 1
img_size:
    value: 224
init_device:
    value: cuda
joints:
    value:
        - '{''arm.position'': 14}'
        - '{''effector.position'': 2}'
load_checkpoint_path:
    value: null
local_rank:
    value: 0
lora_alpha:
    value: 32
lora_dropout:
    value: 0.05
lora_rank:
    value: 16
lora_target_modules:
    value: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
lora_target_scope:
    value: model.qwenvl_with_expert.qwen_expert.model.layers
lora_trainable_modules:
    value: model.state_proj,model.action_in_proj,model.action_out_proj,model.action_time_mlp_in,model.action_time_mlp_out,model.time_mlp_in,model.time_mlp_out
loss_type:
    value: fm
lr:
    value: 2e-05
lr_decay_ratio:
    value: 1
lr_decay_style:
    value: constant
lr_min:
    value: 1e-07
lr_start:
    value: 0
lr_warmup_ratio:
    value: 0
max_action_dim:
    value: 75
max_checkpoints_to_keep:
    value: 5
max_grad_norm:
    value: 1
max_seq_len:
    value: 2048
max_state_dim:
    value: 75
max_steps:
    value: 50000
micro_batch_size:
    value: 16
model_assets_dir:
    value: ../../../output/kuavo_lingbotvla/task1_bottle_lora/model_assets
model_path:
    value: /root/bayes-tmp/jiayi/hf_models/lingbot-vla-4b
module_fsdp_enable:
    value: true
moge_path:
    value: null
morgbd_path:
    value: null
norm_qkv:
    value: false
norm_stats_file:
    value: assets/norm_stats/kuavo.json
norm_type:
    value: meanstd
nosplit_gate_liner:
    value: false
num_steps:
    value: 10
num_train_epochs:
    value: 999999999
num_workers:
    value: 4
optimizer:
    value: adamw
output_dir:
    value: ../../../output/kuavo_lingbotvla/task1_bottle_lora
pin_memory:
    value: true
pipeline_parallel_size:
    value: 1
post_training:
    value: true
prefetch_factor:
    value: 4
profile_end_step:
    value: 2
profile_profile_memory:
    value: true
profile_record_shapes:
    value: true
profile_start_step:
    value: 1
profile_trace_dir:
    value: ./trace
profile_with_stack:
    value: true
resize_imgs_with_padding:
    value:
        - 224
        - 224
resume_dataloader_state:
    value: true
rmpad:
    value: false
rmpad_with_pos_ids:
    value: false
robot_config_root:
    value: configs/robot_configs
save_checkpoint_path:
    value: ../../../output/kuavo_lingbotvla/task1_bottle_lora/checkpoints
save_epochs:
    value: 0
save_hf_weights:
    value: true
save_steps:
    value: 10000
seed:
    value: 42
separate_time_proj:
    value: false
split_gate_liner:
    value: false
stable_train_steps:
    value: 100000
tensor_parallel_size:
    value: 1
text_keys:
    value: messages
tokenizer_max_length:
    value: 72
tokenizer_path:
    value: /root/bayes-tmp/jiayi/hf_models/Qwen2.5-VL-3B-Instruct
train_expert_only:
    value: false
train_path:
    value: /root/bayes-tmp/kuavo_dataset/task1_bottle_pick_lerobot/lerobot_v3.0
train_size:
    value: 10000000
train_state_proj:
    value: true
ulysses_parallel_size:
    value: 1
use_cache:
    value: true
use_compile:
    value: true
use_delta_joint_actions_aloha:
    value: false
use_lm_head:
    value: false
use_lora:
    value: true
use_wandb:
    value: true
vit_lr:
    value: 1e-06
vlm_causal:
    value: false
vlm_repo_id:
    value: null
vocab_size:
    value: 0
wandb_name:
    value: package_lora
wandb_project:
    value: lingbotvla
weight_decay:
    value: 0
world_size:
    value: 1
